services:
  book-worms-db:
    image: postgres:17
    container_name: book-worms-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - book-worms-db-data:/var/lib/postgresql/data
    networks:
      - internal

  bookworms-service:
    image: softwaredevdad/bookworms-api:latest
    # build: ./
    container_name: booksworms-service
    ports:
      - "8088:8088"
    networks:
      - internal
    depends_on:
      - book-worms-db
      - pgadmin
      - mail-dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes: # Add this section
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal
    depends_on:
      - book-worms-db

  mail-dev:
    container_name: mail-dev-bookworms
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - internal

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:9090
      KC_HOSTNAME_STRICT: false
    networks:
      - internal
    depends_on:
      - book-worms-db
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command:
      # Initiates Keycloak server
      - "start-dev"
      - "--import-realm"

networks:
  internal:
    driver: bridge
    name: internal # Forces exact network name (no project prefix)ernal

volumes:
  book-worms-db-data:
    driver: local
  pgadmin-data: # Allows us to persist pgadmin data so need to re-add servers every single time
    driver: local
